//! macOS-only glue: pasteboard change detection, focus handling, the global
//! hotkey and simulated keystrokes.

use anyhow::{Result, anyhow, bail};
use core_foundation::base::TCFType;
use core_foundation::boolean::CFBoolean;
use core_foundation::dictionary::{CFDictionary, CFDictionaryRef};
use core_foundation::string::CFString;
use core_graphics::event::{CGEvent, CGEventFlags, CGEventTapLocation, CGKeyCode};
use core_graphics::event_source::{CGEventSource, CGEventSourceStateID};
use std::thread::sleep;
use std::time::{Duration, Instant};
use global_hotkey::hotkey::{Code, HotKey, Modifiers};
use global_hotkey::{GlobalHotKeyEvent, GlobalHotKeyManager, HotKeyState};
use objc2_app_kit::{
    NSApplication, NSApplicationActivationOptions, NSPasteboard, NSRunningApplication, NSWorkspace,
};
use objc2_foundation::MainThreadMarker;

/// Pasteboard types that password managers use to mark secrets
/// (see nspasteboard.org).
const SKIP_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

const KEY_V: CGKeyCode = 9; // kVK_ANSI_V
const KEY_RETURN: CGKeyCode = 36;
const KEY_TAB: CGKeyCode = 48;

#[link(name = "ApplicationServices", kind = "framework")]
unsafe extern "C" {
    fn AXIsProcessTrustedWithOptions(options: CFDictionaryRef) -> bool;
    fn CGEventSourceFlagsState(state: i32) -> u64;
}

/// Whether we may send keystrokes. With `prompt`, macOS shows its
/// "allow Accessibility" dialog if we may not.
pub fn accessibility_trusted(prompt: bool) -> bool {
    let options = CFDictionary::from_CFType_pairs(&[(
        CFString::new("AXTrustedCheckOptionPrompt"),
        CFBoolean::from(prompt),
    )]);
    unsafe { AXIsProcessTrustedWithOptions(options.as_concrete_TypeRef()) }
}

/// Waits (up to 2s) until the user lets go of ⌘/⇧/⌥/⌃, otherwise our
/// keystrokes would combine with the keys still held from the shortcut.
fn wait_for_modifiers_released() {
    const MODIFIERS: u64 = 0x0002_0000 | 0x0004_0000 | 0x0008_0000 | 0x0010_0000;
    const COMBINED_SESSION_STATE: i32 = 0;
    let deadline = Instant::now() + Duration::from_secs(2);
    while unsafe { CGEventSourceFlagsState(COMBINED_SESSION_STATE) } & MODIFIERS != 0
        && Instant::now() < deadline
    {
        sleep(Duration::from_millis(10));
    }
}

fn source() -> Result<CGEventSource> {
    if !accessibility_trusted(true) {
        bail!("Accessibility permission is needed to paste/type (System Settings → Privacy & Security → Accessibility)");
    }
    CGEventSource::new(CGEventSourceStateID::HIDSystemState).map_err(|_| anyhow!("no event source"))
}

fn post_key(src: &CGEventSource, key: CGKeyCode, flags: CGEventFlags, text: Option<&str>) -> Result<()> {
    for down in [true, false] {
        let event = CGEvent::new_keyboard_event(src.clone(), key, down)
            .map_err(|_| anyhow!("cannot create key event"))?;
        if let Some(text) = text {
            event.set_string(text);
        }
        event.set_flags(flags);
        event.post(CGEventTapLocation::HID);
    }
    Ok(())
}

pub fn send_paste() -> Result<()> {
    let src = source()?;
    wait_for_modifiers_released();
    post_key(&src, KEY_V, CGEventFlags::CGEventFlagCommand, None)
}

/// Types the text one character at a time, like a (fast) human would.
pub fn type_text(text: &str) -> Result<()> {
    let src = source()?;
    wait_for_modifiers_released();
    let none = CGEventFlags::CGEventFlagNull;
    let mut buf = [0u8; 4];
    for ch in text.chars() {
        match ch {
            '\r' => continue, // \r\n → one Return
            '\n' => post_key(&src, KEY_RETURN, none, None)?,
            '\t' => post_key(&src, KEY_TAB, none, None)?,
            _ => post_key(&src, 0, none, Some(ch.encode_utf8(&mut buf)))?,
        }
        sleep(Duration::from_millis(3));
    }
    Ok(())
}

pub fn change_count() -> isize {
    NSPasteboard::generalPasteboard().changeCount()
}

pub fn should_skip_current() -> bool {
    let Some(types) = NSPasteboard::generalPasteboard().types() else {
        return false;
    };
    types.iter().any(|t| SKIP_TYPES.contains(&t.to_string().as_str()))
}

pub fn frontmost_pid() -> Option<i32> {
    let app = NSWorkspace::sharedWorkspace().frontmostApplication()?;
    Some(app.processIdentifier())
}

pub fn activate(pid: i32) {
    if let Some(app) = NSRunningApplication::runningApplicationWithProcessIdentifier(pid) {
        #[allow(deprecated)]
        app.activateWithOptions(NSApplicationActivationOptions::ActivateIgnoringOtherApps);
    }
}

/// Brings this (Dock-less) app to the front. Main thread only.
pub fn activate_self() {
    if let Some(mtm) = MainThreadMarker::new() {
        let app = NSApplication::sharedApplication(mtm);
        app.activate();
        #[allow(deprecated)]
        app.activateIgnoringOtherApps(true);
    }
}

/// Registers Cmd+Shift+V. Must be called on the main thread before the event
/// loop starts; keep the returned manager alive.
pub fn register_hotkey(on_hotkey: impl Fn() + Send + Sync + 'static) -> Result<GlobalHotKeyManager> {
    let manager = GlobalHotKeyManager::new()?;
    manager.register(HotKey::new(Some(Modifiers::SUPER | Modifiers::SHIFT), Code::KeyV))?;
    GlobalHotKeyEvent::set_event_handler(Some(move |event: GlobalHotKeyEvent| {
        if event.state == HotKeyState::Pressed {
            on_hotkey();
        }
    }));
    eprintln!("clipr: hotkey Cmd+Shift+V");
    Ok(manager)
}
